<template>
  <svg height="24px" viewBox="0 0 100 100" width="24px" xmlns="http://www.w3.org/2000/svg">
    <circle
      cx="50"
      cy="50"
      fill="none"
      r="35"
      stroke="currentColor"
      stroke-dasharray="164.93361431346415 56.97787143782138"
      stroke-width="10"
    >
      <animateTransform
        attributeName="transform"
        dur="0.8s"
        keyTimes="0;1"
        repeatCount="indefinite"
        type="rotate"
        values="0 50 50;360 50 50"
      ></animateTransform>
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>

<script lang="ts" setup></script>
